// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mdb.proto

package com.telenav.mdb.protos;

public final class PoiProtos {
  private PoiProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PoiOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string id = 1;
    boolean hasId();
    String getId();
    
    // required int64 node_index = 2;
    boolean hasNodeIndex();
    long getNodeIndex();
    
    // required string city = 3;
    boolean hasCity();
    String getCity();
    
    // required string state = 4;
    boolean hasState();
    String getState();
    
    // required string vendor = 5;
    boolean hasVendor();
    String getVendor();
    
    // optional int32 version = 7;
    boolean hasVersion();
    int getVersion();
    
    // repeated .mdb.PhoneNumber phone = 8;
    java.util.List<com.telenav.mdb.protos.PoiProtos.PhoneNumber> 
        getPhoneList();
    com.telenav.mdb.protos.PoiProtos.PhoneNumber getPhone(int index);
    int getPhoneCount();
    java.util.List<? extends com.telenav.mdb.protos.PoiProtos.PhoneNumberOrBuilder> 
        getPhoneOrBuilderList();
    com.telenav.mdb.protos.PoiProtos.PhoneNumberOrBuilder getPhoneOrBuilder(
        int index);
  }
  public static final class Poi extends
      com.google.protobuf.GeneratedMessage
      implements PoiOrBuilder {
    // Use Poi.newBuilder() to construct.
    private Poi(Builder builder) {
      super(builder);
    }
    private Poi(boolean noInit) {}
    
    private static final Poi defaultInstance;
    public static Poi getDefaultInstance() {
      return defaultInstance;
    }
    
    public Poi getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.telenav.mdb.protos.PoiProtos.internal_static_mdb_Poi_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.telenav.mdb.protos.PoiProtos.internal_static_mdb_Poi_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int64 node_index = 2;
    public static final int NODE_INDEX_FIELD_NUMBER = 2;
    private long nodeIndex_;
    public boolean hasNodeIndex() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getNodeIndex() {
      return nodeIndex_;
    }
    
    // required string city = 3;
    public static final int CITY_FIELD_NUMBER = 3;
    private java.lang.Object city_;
    public boolean hasCity() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getCity() {
      java.lang.Object ref = city_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          city_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string state = 4;
    public static final int STATE_FIELD_NUMBER = 4;
    private java.lang.Object state_;
    public boolean hasState() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getState() {
      java.lang.Object ref = state_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          state_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getStateBytes() {
      java.lang.Object ref = state_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        state_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string vendor = 5;
    public static final int VENDOR_FIELD_NUMBER = 5;
    private java.lang.Object vendor_;
    public boolean hasVendor() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getVendor() {
      java.lang.Object ref = vendor_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          vendor_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getVendorBytes() {
      java.lang.Object ref = vendor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        vendor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 version = 7;
    public static final int VERSION_FIELD_NUMBER = 7;
    private int version_;
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getVersion() {
      return version_;
    }
    
    // repeated .mdb.PhoneNumber phone = 8;
    public static final int PHONE_FIELD_NUMBER = 8;
    private java.util.List<com.telenav.mdb.protos.PoiProtos.PhoneNumber> phone_;
    public java.util.List<com.telenav.mdb.protos.PoiProtos.PhoneNumber> getPhoneList() {
      return phone_;
    }
    public java.util.List<? extends com.telenav.mdb.protos.PoiProtos.PhoneNumberOrBuilder> 
        getPhoneOrBuilderList() {
      return phone_;
    }
    public int getPhoneCount() {
      return phone_.size();
    }
    public com.telenav.mdb.protos.PoiProtos.PhoneNumber getPhone(int index) {
      return phone_.get(index);
    }
    public com.telenav.mdb.protos.PoiProtos.PhoneNumberOrBuilder getPhoneOrBuilder(
        int index) {
      return phone_.get(index);
    }
    
    private void initFields() {
      id_ = "";
      nodeIndex_ = 0L;
      city_ = "";
      state_ = "";
      vendor_ = "";
      version_ = 0;
      phone_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNodeIndex()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCity()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVendor()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPhoneCount(); i++) {
        if (!getPhone(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, nodeIndex_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getCityBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getStateBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getVendorBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(7, version_);
      }
      for (int i = 0; i < phone_.size(); i++) {
        output.writeMessage(8, phone_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, nodeIndex_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getCityBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getStateBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getVendorBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, version_);
      }
      for (int i = 0; i < phone_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, phone_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.telenav.mdb.protos.PoiProtos.Poi parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.telenav.mdb.protos.PoiProtos.Poi parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.telenav.mdb.protos.PoiProtos.Poi parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.telenav.mdb.protos.PoiProtos.Poi parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.telenav.mdb.protos.PoiProtos.Poi parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.telenav.mdb.protos.PoiProtos.Poi parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.telenav.mdb.protos.PoiProtos.Poi parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.telenav.mdb.protos.PoiProtos.Poi parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.telenav.mdb.protos.PoiProtos.Poi parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.telenav.mdb.protos.PoiProtos.Poi parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.telenav.mdb.protos.PoiProtos.Poi prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.telenav.mdb.protos.PoiProtos.PoiOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.telenav.mdb.protos.PoiProtos.internal_static_mdb_Poi_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.telenav.mdb.protos.PoiProtos.internal_static_mdb_Poi_fieldAccessorTable;
      }
      
      // Construct using com.telenav.mdb.protos.PoiProtos.Poi.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPhoneFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        nodeIndex_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        city_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        state_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        vendor_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        if (phoneBuilder_ == null) {
          phone_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          phoneBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.telenav.mdb.protos.PoiProtos.Poi.getDescriptor();
      }
      
      public com.telenav.mdb.protos.PoiProtos.Poi getDefaultInstanceForType() {
        return com.telenav.mdb.protos.PoiProtos.Poi.getDefaultInstance();
      }
      
      public com.telenav.mdb.protos.PoiProtos.Poi build() {
        com.telenav.mdb.protos.PoiProtos.Poi result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.telenav.mdb.protos.PoiProtos.Poi buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.telenav.mdb.protos.PoiProtos.Poi result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.telenav.mdb.protos.PoiProtos.Poi buildPartial() {
        com.telenav.mdb.protos.PoiProtos.Poi result = new com.telenav.mdb.protos.PoiProtos.Poi(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.nodeIndex_ = nodeIndex_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.city_ = city_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.vendor_ = vendor_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.version_ = version_;
        if (phoneBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040)) {
            phone_ = java.util.Collections.unmodifiableList(phone_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.phone_ = phone_;
        } else {
          result.phone_ = phoneBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.telenav.mdb.protos.PoiProtos.Poi) {
          return mergeFrom((com.telenav.mdb.protos.PoiProtos.Poi)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.telenav.mdb.protos.PoiProtos.Poi other) {
        if (other == com.telenav.mdb.protos.PoiProtos.Poi.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasNodeIndex()) {
          setNodeIndex(other.getNodeIndex());
        }
        if (other.hasCity()) {
          setCity(other.getCity());
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasVendor()) {
          setVendor(other.getVendor());
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (phoneBuilder_ == null) {
          if (!other.phone_.isEmpty()) {
            if (phone_.isEmpty()) {
              phone_ = other.phone_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensurePhoneIsMutable();
              phone_.addAll(other.phone_);
            }
            onChanged();
          }
        } else {
          if (!other.phone_.isEmpty()) {
            if (phoneBuilder_.isEmpty()) {
              phoneBuilder_.dispose();
              phoneBuilder_ = null;
              phone_ = other.phone_;
              bitField0_ = (bitField0_ & ~0x00000040);
              phoneBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPhoneFieldBuilder() : null;
            } else {
              phoneBuilder_.addAllMessages(other.phone_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasNodeIndex()) {
          
          return false;
        }
        if (!hasCity()) {
          
          return false;
        }
        if (!hasState()) {
          
          return false;
        }
        if (!hasVendor()) {
          
          return false;
        }
        for (int i = 0; i < getPhoneCount(); i++) {
          if (!getPhone(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              nodeIndex_ = input.readInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              city_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              state_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              vendor_ = input.readBytes();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000020;
              version_ = input.readInt32();
              break;
            }
            case 66: {
              com.telenav.mdb.protos.PoiProtos.PhoneNumber.Builder subBuilder = com.telenav.mdb.protos.PoiProtos.PhoneNumber.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPhone(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string id = 1;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // required int64 node_index = 2;
      private long nodeIndex_ ;
      public boolean hasNodeIndex() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getNodeIndex() {
        return nodeIndex_;
      }
      public Builder setNodeIndex(long value) {
        bitField0_ |= 0x00000002;
        nodeIndex_ = value;
        onChanged();
        return this;
      }
      public Builder clearNodeIndex() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nodeIndex_ = 0L;
        onChanged();
        return this;
      }
      
      // required string city = 3;
      private java.lang.Object city_ = "";
      public boolean hasCity() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getCity() {
        java.lang.Object ref = city_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          city_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCity(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        city_ = value;
        onChanged();
        return this;
      }
      public Builder clearCity() {
        bitField0_ = (bitField0_ & ~0x00000004);
        city_ = getDefaultInstance().getCity();
        onChanged();
        return this;
      }
      void setCity(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        city_ = value;
        onChanged();
      }
      
      // required string state = 4;
      private java.lang.Object state_ = "";
      public boolean hasState() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getState() {
        java.lang.Object ref = state_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          state_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setState(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        state_ = value;
        onChanged();
        return this;
      }
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000008);
        state_ = getDefaultInstance().getState();
        onChanged();
        return this;
      }
      void setState(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        state_ = value;
        onChanged();
      }
      
      // required string vendor = 5;
      private java.lang.Object vendor_ = "";
      public boolean hasVendor() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getVendor() {
        java.lang.Object ref = vendor_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          vendor_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setVendor(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        vendor_ = value;
        onChanged();
        return this;
      }
      public Builder clearVendor() {
        bitField0_ = (bitField0_ & ~0x00000010);
        vendor_ = getDefaultInstance().getVendor();
        onChanged();
        return this;
      }
      void setVendor(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        vendor_ = value;
        onChanged();
      }
      
      // optional int32 version = 7;
      private int version_ ;
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getVersion() {
        return version_;
      }
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000020;
        version_ = value;
        onChanged();
        return this;
      }
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000020);
        version_ = 0;
        onChanged();
        return this;
      }
      
      // repeated .mdb.PhoneNumber phone = 8;
      private java.util.List<com.telenav.mdb.protos.PoiProtos.PhoneNumber> phone_ =
        java.util.Collections.emptyList();
      private void ensurePhoneIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          phone_ = new java.util.ArrayList<com.telenav.mdb.protos.PoiProtos.PhoneNumber>(phone_);
          bitField0_ |= 0x00000040;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.telenav.mdb.protos.PoiProtos.PhoneNumber, com.telenav.mdb.protos.PoiProtos.PhoneNumber.Builder, com.telenav.mdb.protos.PoiProtos.PhoneNumberOrBuilder> phoneBuilder_;
      
      public java.util.List<com.telenav.mdb.protos.PoiProtos.PhoneNumber> getPhoneList() {
        if (phoneBuilder_ == null) {
          return java.util.Collections.unmodifiableList(phone_);
        } else {
          return phoneBuilder_.getMessageList();
        }
      }
      public int getPhoneCount() {
        if (phoneBuilder_ == null) {
          return phone_.size();
        } else {
          return phoneBuilder_.getCount();
        }
      }
      public com.telenav.mdb.protos.PoiProtos.PhoneNumber getPhone(int index) {
        if (phoneBuilder_ == null) {
          return phone_.get(index);
        } else {
          return phoneBuilder_.getMessage(index);
        }
      }
      public Builder setPhone(
          int index, com.telenav.mdb.protos.PoiProtos.PhoneNumber value) {
        if (phoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneIsMutable();
          phone_.set(index, value);
          onChanged();
        } else {
          phoneBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setPhone(
          int index, com.telenav.mdb.protos.PoiProtos.PhoneNumber.Builder builderForValue) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.set(index, builderForValue.build());
          onChanged();
        } else {
          phoneBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addPhone(com.telenav.mdb.protos.PoiProtos.PhoneNumber value) {
        if (phoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneIsMutable();
          phone_.add(value);
          onChanged();
        } else {
          phoneBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addPhone(
          int index, com.telenav.mdb.protos.PoiProtos.PhoneNumber value) {
        if (phoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneIsMutable();
          phone_.add(index, value);
          onChanged();
        } else {
          phoneBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addPhone(
          com.telenav.mdb.protos.PoiProtos.PhoneNumber.Builder builderForValue) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.add(builderForValue.build());
          onChanged();
        } else {
          phoneBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addPhone(
          int index, com.telenav.mdb.protos.PoiProtos.PhoneNumber.Builder builderForValue) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.add(index, builderForValue.build());
          onChanged();
        } else {
          phoneBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllPhone(
          java.lang.Iterable<? extends com.telenav.mdb.protos.PoiProtos.PhoneNumber> values) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          super.addAll(values, phone_);
          onChanged();
        } else {
          phoneBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearPhone() {
        if (phoneBuilder_ == null) {
          phone_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          phoneBuilder_.clear();
        }
        return this;
      }
      public Builder removePhone(int index) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.remove(index);
          onChanged();
        } else {
          phoneBuilder_.remove(index);
        }
        return this;
      }
      public com.telenav.mdb.protos.PoiProtos.PhoneNumber.Builder getPhoneBuilder(
          int index) {
        return getPhoneFieldBuilder().getBuilder(index);
      }
      public com.telenav.mdb.protos.PoiProtos.PhoneNumberOrBuilder getPhoneOrBuilder(
          int index) {
        if (phoneBuilder_ == null) {
          return phone_.get(index);  } else {
          return phoneBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.telenav.mdb.protos.PoiProtos.PhoneNumberOrBuilder> 
           getPhoneOrBuilderList() {
        if (phoneBuilder_ != null) {
          return phoneBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(phone_);
        }
      }
      public com.telenav.mdb.protos.PoiProtos.PhoneNumber.Builder addPhoneBuilder() {
        return getPhoneFieldBuilder().addBuilder(
            com.telenav.mdb.protos.PoiProtos.PhoneNumber.getDefaultInstance());
      }
      public com.telenav.mdb.protos.PoiProtos.PhoneNumber.Builder addPhoneBuilder(
          int index) {
        return getPhoneFieldBuilder().addBuilder(
            index, com.telenav.mdb.protos.PoiProtos.PhoneNumber.getDefaultInstance());
      }
      public java.util.List<com.telenav.mdb.protos.PoiProtos.PhoneNumber.Builder> 
           getPhoneBuilderList() {
        return getPhoneFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.telenav.mdb.protos.PoiProtos.PhoneNumber, com.telenav.mdb.protos.PoiProtos.PhoneNumber.Builder, com.telenav.mdb.protos.PoiProtos.PhoneNumberOrBuilder> 
          getPhoneFieldBuilder() {
        if (phoneBuilder_ == null) {
          phoneBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.telenav.mdb.protos.PoiProtos.PhoneNumber, com.telenav.mdb.protos.PoiProtos.PhoneNumber.Builder, com.telenav.mdb.protos.PoiProtos.PhoneNumberOrBuilder>(
                  phone_,
                  ((bitField0_ & 0x00000040) == 0x00000040),
                  getParentForChildren(),
                  isClean());
          phone_ = null;
        }
        return phoneBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:mdb.Poi)
    }
    
    static {
      defaultInstance = new Poi(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:mdb.Poi)
  }
  
  public interface PhoneNumberOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string phone = 1;
    boolean hasPhone();
    String getPhone();
  }
  public static final class PhoneNumber extends
      com.google.protobuf.GeneratedMessage
      implements PhoneNumberOrBuilder {
    // Use PhoneNumber.newBuilder() to construct.
    private PhoneNumber(Builder builder) {
      super(builder);
    }
    private PhoneNumber(boolean noInit) {}
    
    private static final PhoneNumber defaultInstance;
    public static PhoneNumber getDefaultInstance() {
      return defaultInstance;
    }
    
    public PhoneNumber getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.telenav.mdb.protos.PoiProtos.internal_static_mdb_PhoneNumber_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.telenav.mdb.protos.PoiProtos.internal_static_mdb_PhoneNumber_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string phone = 1;
    public static final int PHONE_FIELD_NUMBER = 1;
    private java.lang.Object phone_;
    public boolean hasPhone() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getPhone() {
      java.lang.Object ref = phone_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          phone_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPhoneBytes() {
      java.lang.Object ref = phone_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        phone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      phone_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasPhone()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPhoneBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPhoneBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.telenav.mdb.protos.PoiProtos.PhoneNumber parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.telenav.mdb.protos.PoiProtos.PhoneNumber parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.telenav.mdb.protos.PoiProtos.PhoneNumber parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.telenav.mdb.protos.PoiProtos.PhoneNumber parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.telenav.mdb.protos.PoiProtos.PhoneNumber parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.telenav.mdb.protos.PoiProtos.PhoneNumber parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.telenav.mdb.protos.PoiProtos.PhoneNumber parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.telenav.mdb.protos.PoiProtos.PhoneNumber parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.telenav.mdb.protos.PoiProtos.PhoneNumber parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.telenav.mdb.protos.PoiProtos.PhoneNumber parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.telenav.mdb.protos.PoiProtos.PhoneNumber prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.telenav.mdb.protos.PoiProtos.PhoneNumberOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.telenav.mdb.protos.PoiProtos.internal_static_mdb_PhoneNumber_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.telenav.mdb.protos.PoiProtos.internal_static_mdb_PhoneNumber_fieldAccessorTable;
      }
      
      // Construct using com.telenav.mdb.protos.PoiProtos.PhoneNumber.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        phone_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.telenav.mdb.protos.PoiProtos.PhoneNumber.getDescriptor();
      }
      
      public com.telenav.mdb.protos.PoiProtos.PhoneNumber getDefaultInstanceForType() {
        return com.telenav.mdb.protos.PoiProtos.PhoneNumber.getDefaultInstance();
      }
      
      public com.telenav.mdb.protos.PoiProtos.PhoneNumber build() {
        com.telenav.mdb.protos.PoiProtos.PhoneNumber result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.telenav.mdb.protos.PoiProtos.PhoneNumber buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.telenav.mdb.protos.PoiProtos.PhoneNumber result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.telenav.mdb.protos.PoiProtos.PhoneNumber buildPartial() {
        com.telenav.mdb.protos.PoiProtos.PhoneNumber result = new com.telenav.mdb.protos.PoiProtos.PhoneNumber(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.phone_ = phone_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.telenav.mdb.protos.PoiProtos.PhoneNumber) {
          return mergeFrom((com.telenav.mdb.protos.PoiProtos.PhoneNumber)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.telenav.mdb.protos.PoiProtos.PhoneNumber other) {
        if (other == com.telenav.mdb.protos.PoiProtos.PhoneNumber.getDefaultInstance()) return this;
        if (other.hasPhone()) {
          setPhone(other.getPhone());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasPhone()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              phone_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string phone = 1;
      private java.lang.Object phone_ = "";
      public boolean hasPhone() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getPhone() {
        java.lang.Object ref = phone_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          phone_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPhone(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        phone_ = value;
        onChanged();
        return this;
      }
      public Builder clearPhone() {
        bitField0_ = (bitField0_ & ~0x00000001);
        phone_ = getDefaultInstance().getPhone();
        onChanged();
        return this;
      }
      void setPhone(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        phone_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:mdb.PhoneNumber)
    }
    
    static {
      defaultInstance = new PhoneNumber(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:mdb.PhoneNumber)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mdb_Poi_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mdb_Poi_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mdb_PhoneNumber_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mdb_PhoneNumber_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tmdb.proto\022\003mdb\"\204\001\n\003Poi\022\n\n\002id\030\001 \002(\t\022\022\n\n" +
      "node_index\030\002 \002(\003\022\014\n\004city\030\003 \002(\t\022\r\n\005state\030" +
      "\004 \002(\t\022\016\n\006vendor\030\005 \002(\t\022\017\n\007version\030\007 \001(\005\022\037" +
      "\n\005phone\030\010 \003(\0132\020.mdb.PhoneNumber\"\034\n\013Phone" +
      "Number\022\r\n\005phone\030\001 \002(\tB#\n\026com.telenav.mdb" +
      ".protosB\tPoiProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_mdb_Poi_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_mdb_Poi_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mdb_Poi_descriptor,
              new java.lang.String[] { "Id", "NodeIndex", "City", "State", "Vendor", "Version", "Phone", },
              com.telenav.mdb.protos.PoiProtos.Poi.class,
              com.telenav.mdb.protos.PoiProtos.Poi.Builder.class);
          internal_static_mdb_PhoneNumber_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_mdb_PhoneNumber_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mdb_PhoneNumber_descriptor,
              new java.lang.String[] { "Phone", },
              com.telenav.mdb.protos.PoiProtos.PhoneNumber.class,
              com.telenav.mdb.protos.PoiProtos.PhoneNumber.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
